### ISSUE TITLE
Release: v2.0.0

### ISSUE THREAD

**Issue by azat-io** [azat-io/eslint-plugin-perfectionist#32]
- [x] Add rule for sorting Astro attributes (#36)
- [x] Add rule for sorting Svelte attributes (#26)
- [x] Add rule for sorting Vue attributes (#55)
- [x] Rename `sort-map-elements` rule to `sort-maps` (#34)
- [x] Move from `callback`, `multiline` and `shorthand` options to `groups` option in `sort-jsx-props` rule (#40)
- [x] Remove `read-tsconfig` feature in `sort-imports` rule (#35)
- [x] Support `require` in `sort-imports` rule (#38)
- [x] Move to typescript-eslint v6 (#37)
- [x] Add option for disabling sorting in styled-components in `sort-objects` rule (#44)
- [x] Add `groups` option in `sort-interfaces` rule (#60)
- [x] Add `groups` option in  `sort-object-types` rule (#63)
- [x] Move from `always-on-top` option to `groups` option in `sort-objects` rule (#43)

**Comment by azat-io** [comment]
It might also be worth adding a rule for sorting MDX props.

**Comment by 13OnTheCode** [comment]
May I ask what is the reason for considering the removal of `read-tsconfig` ?

**Comment by azat-io** [comment]
@13OnTheCode I don't think it's a good practice. It makes ESLint's work slow. Maybe it is better to set the value manually than to read the `tsconfig.json` file every time. What do you think about this?

**Comment by 13OnTheCode** [comment]
@azat-io Yes, you are right. I apologize for not carefully reading the source code earlier. I mistakenly thought that reading the TSConfig configuration file served a purpose beyond retrieving `compilerOptions.paths`.

Deleting it is indeed a good idea because its purpose is almost identical to `internal-pattern`, and people usually only set `~/**` or `@/**`.

**Comment by brightsider** [comment]
could you help me to use next version now?
I installed it by:
` "eslint-plugin-perfectionist": "github:azat-io/eslint-plugin-perfectionist#next"`
package-lock.json has:
`"resolved": "git+ssh://git@github.com/azat-io/eslint-plugin-perfectionist.git#3210ff3b1f69702c0e4dfe7666c152828895231d",`
but folder eslint-plugin-prettier didn't contain eslint-plugin-prettier.js

**Comment by azat-io** [comment]
We don't store dist folder in the repository. I'm planning to publish a version under the next flag early next week.

**Comment by azat-io** [comment]
Will be released soon.

**Comment by azat-io** [comment]
Released in [v2.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v2.0.0)
